openapi: 3.0.3
info:
  title: Pharmacy ERP API (v2)
  version: 0.1.0
  description: >-
    Versioned REST API for the Pharmacy ERP. This spec is the source of truth for the v2 endpoints.
servers:
  - url: /api/v2
paths:
  /auth/login:
    post:
      summary: Authenticate and issue tokens
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      user:
                        type: object
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
        '401':
          description: Invalid credentials
  /auth/refresh:
    post:
      summary: Refresh access token
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [refreshToken]
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Refreshed
  /ui/bootstrap:
    get:
      summary: Fetch user bootstrap (menus, permissions, features, me)
      tags: [UI]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Bootstrap payload
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

