-- Seed CRUD permissions for core modules
INSERT IGNORE INTO permissions (name, description, category) VALUES
  ('products:create', 'Create products', 'Products'),
  ('products:read', 'Read products', 'Products'),
  ('products:update', 'Update products', 'Products'),
  ('products:delete', 'Delete products', 'Products'),
  ('category:create', 'Create categories', 'Categories'),
  ('category:read', 'Read categories', 'Categories'),
  ('category:update', 'Update categories', 'Categories'),
  ('category:delete', 'Delete categories', 'Categories'),
  ('inventory:create', 'Create inventory entries', 'Inventory'),
  ('inventory:read', 'Read inventory', 'Inventory'),
  ('inventory:update', 'Update inventory', 'Inventory'),
  ('inventory:delete', 'Delete inventory entries', 'Inventory'),
  ('sales:create', 'Create sales', 'Sales'),
  ('sales:read', 'Read sales', 'Sales'),
  ('sales:update', 'Update sales', 'Sales'),
  ('sales:delete', 'Delete sales', 'Sales'),
  ('customers:create', 'Create customers', 'Customers'),
  ('customers:read', 'Read customers', 'Customers'),
  ('customers:update', 'Update customers', 'Customers'),
  ('customers:delete', 'Delete customers', 'Customers'),
  ('branches:create', 'Create branches', 'Branches'),
  ('branches:read', 'Read branches', 'Branches'),
  ('branches:update', 'Update branches', 'Branches'),
  ('branches:delete', 'Delete branches', 'Branches'),
  ('suppliers:create', 'Create suppliers', 'Suppliers'),
  ('suppliers:read', 'Read suppliers', 'Suppliers'),
  ('suppliers:update', 'Update suppliers', 'Suppliers'),
  ('suppliers:delete', 'Delete suppliers', 'Suppliers'),
  ('users:create', 'Create users', 'Users'),
  ('users:read', 'Read users', 'Users'),
  ('users:update', 'Update users', 'Users'),
  ('users:delete', 'Delete users', 'Users'),
  ('roles:create', 'Create roles', 'Roles'),
  ('roles:read', 'Read roles', 'Roles'),
  ('roles:update', 'Update roles', 'Roles'),
  ('roles:delete', 'Delete roles', 'Roles'),
  ('payments:create', 'Create payments', 'Payments'),
  ('payments:read', 'Read payments', 'Payments'),
  ('payments:update', 'Update payments', 'Payments'),
  ('payments:delete', 'Delete payments', 'Payments'),
  ('settings:create', 'Create settings', 'Settings'),
  ('settings:read', 'Read settings', 'Settings'),
  ('settings:update', 'Update settings', 'Settings'),
  ('settings:delete', 'Delete settings', 'Settings'),
  ('purchases:create', 'Create purchases', 'Purchases'),
  ('purchases:read', 'Read purchases', 'Purchases'),
  ('purchases:update', 'Update purchases', 'Purchases'),
  ('purchases:delete', 'Delete purchases', 'Purchases'),
  ('purchase_orders:create', 'Create purchase orders', 'Purchase Orders'),
  ('purchase_orders:read', 'Read purchase orders', 'Purchase Orders'),
  ('purchase_orders:update', 'Update purchase orders', 'Purchase Orders'),
  ('purchase_orders:delete', 'Delete purchase orders', 'Purchase Orders'),
  ('transfers:create', 'Create transfers', 'Transfers'),
  ('transfers:read', 'Read transfers', 'Transfers'),
  ('transfers:update', 'Update transfers', 'Transfers'),
  ('transfers:delete', 'Delete transfers', 'Transfers');
